name: 🧩 USE Component Definition
description: Define a new USE platform component with clear actor interactions and domain classification
title: "[USE_ID] USE Component Title"
labels: ["component", "use-component"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📋 USE Component Definition Template
        
        **USE (Unified Scenario Engineering)** extends BDD with business-friendly language.
        This template ensures your USE component is properly indexed and managed.
        **All fields marked with * are required for automated processing.**
        
        💡 **USE vs BDD**: We use USE terminology (Scenarios, Actors, Domains) but implement with proven BDD tools.

  - type: input
    id: component_id
    attributes:
      label: "USE Component ID *"
      description: "Unique identifier following USE naming convention"
      placeholder: "B_S001_US001, T_S001_API001, U_S001_UX001, T_F001"
    validations:
      required: true

  - type: dropdown
    id: component_type
    attributes:
      label: "USE Component Type *"
      description: "Select the USE component type"
      options:
        - "Business User Story (B_S_US)"
        - "Technical API Component (T_S_API)"
        - "UX Interface Component (U_S_UX)"
        - "Technical Foundation (T_F)"
        - "Business Process (B_S)"
        - "Technical Service (T_S)"
        - "UX Design Pattern (U_S)"
        - "Testing Scenario (TEST)"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: "USE Domain *"
      description: "Which USE domain does this component belong to?"
      options:
        - "Business (B_S) - Human actor scenarios"
        - "Technical (T_S) - System component interactions"
        - "UX (U_S) - User interface and experience"
        - "Foundation (T_F) - Core infrastructure"
        - "Testing (TEST) - Quality assurance scenarios"
    validations:
      required: true

  - type: dropdown
    id: participant
    attributes:
      label: "Primary Actor"
      description: "Who/what is the main USE actor for this component?"
      options:
        - "🏥 Healthcare Organisation"
        - "👩‍⚕️ Job Seeker"
        - "📞 Sales Team"
        - "🔐 Authentication System"
        - "🗄️ Database"
        - "📧 Email System"
        - "💻 Desktop User"
        - "📱 Mobile User"
        - "🎨 Design System"
    validations:
      required: false

  - type: input
    id: title
    attributes:
      label: "USE Component Title *"
      description: "Clear, action-oriented title describing actor interaction"
      placeholder: "Organisation Receives Cold Call, Authentication System Setup, Mobile Navigation Flow"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "USE Component Description *"
      description: "Brief description focusing on actor interactions and value delivered"
      placeholder: "Healthcare Organisation receives initial contact from Bemeda sales team, leading to staffing needs discussion and potential platform onboarding..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Implementation priority for this component"
      options:
        - high
        - medium
        - low
      default: 2

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Current status of this component"
      options:
        - planning
        - in-progress
        - review
        - completed
        - on-hold
      default: 0

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "USE Acceptance Criteria"
      description: "Criteria focusing on actor goal achievement and scenario success"
      placeholder: |
        - [ ] All actors achieve their defined goals
        - [ ] Scenario executes successfully end-to-end
        - [ ] Error handling and edge cases implemented
        - [ ] Integration with parallel scenarios working
        - [ ] USE scenario tests written and passing
        - [ ] Documentation updated with actor interactions
      value: |
        - [ ] All actors achieve their defined goals
        - [ ] Scenario executes successfully end-to-end
        - [ ] Error handling and edge cases implemented
        - [ ] Integration with parallel scenarios working
        - [ ] USE scenario tests written and passing
        - [ ] Documentation updated with actor interactions

  - type: textarea
    id: related_components
    attributes:
      label: "Related USE Components"
      description: "List USE components this depends on or triggers"
      placeholder: "B_S001_US001, T_S001_AUTH001, U_S001_UX001"

  - type: input
    id: figma_url
    attributes:
      label: "Figma/Design URL"
      description: "Link to design files if applicable"
      placeholder: "https://figma.com/..."

  - type: input
    id: spec_url
    attributes:
      label: "Specification URL"
      description: "Link to detailed specification document"
      placeholder: "https://3stones-io.github.io/bemeda_personal/docs/..."

  - type: textarea
    id: metadata_json
    attributes:
      label: "USE Component Metadata (Auto-generated) *"
      description: "This JSON will be automatically generated by GitHub Actions. Do not edit manually."
      value: |
        ```json
        {
          "use_id": "",
          "component_type": "",
          "title": "",
          "description": "",
          "use_domain": "",
          "primary_actor": "",
          "priority": "",
          "status": "",
          "related_components": [],
          "parallel_scenarios": [],
          "actor_goals": [],
          "urls": {
            "figma": "",
            "spec": ""
          },
          "acceptance_criteria": [],
          "tags": [],
          "created_date": "",
          "last_updated": ""
        }
        ```
      render: json
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: "Validation Checklist"
      description: "Please confirm the following before submitting:"
      options:
        - label: "I have followed the USE naming convention (B_S001_US001, T_S001, etc.)"
          required: true
        - label: "I have selected the correct USE component type and domain"
          required: true
        - label: "I have clearly identified the primary actor and their goals"
          required: true
        - label: "I understand this will be automatically processed by USE workflows"
          required: true
        - label: "I have provided all required information marked with *"
          required: true